backend:
  name: github
  repo: sallynorthmore/portfolio-gatsy

media_folder: static/assets
public_folder: assets

collections:
  - name: projects
    label: Projects
    folder: projects
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
